packages:
  - packages/*
  - apps/*

allowBuilds:
  '@parcel/watcher': true
  es5-ext: false
  esbuild: true
  svelte-preprocess: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@the_dissidents/*'

overrides:
  '@the_dissidents/svelte-ui': link:../svelte-ui
